#!/bin/bash

fakeroot dpkg-deb -b terminology-theme-3024Day terminology-theme-3024day_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-3024Night terminology-theme-3024night_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-AdventureTime terminology-theme-adventuretime_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Afterglow terminology-theme-afterglow_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-AlienBlood terminology-theme-alienblood_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Argonaut terminology-theme-argonaut_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Arthur terminology-theme-arthur_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-AtelierSulphurpool terminology-theme-ateliersulphurpool_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Atom terminology-theme-atom_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-AtomOneLight terminology-theme-atomonelight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ayu terminology-theme-ayu_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ayu-light terminology-theme-ayu-light_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Batman terminology-theme-batman_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BelafonteDay terminology-theme-belafonteday_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BelafonteNight terminology-theme-belafontenight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BirdsOfParadise terminology-theme-birdsofparadise_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Blazer terminology-theme-blazer_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BlulocoDark terminology-theme-blulocodark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BlulocoLight terminology-theme-blulocolight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Borland terminology-theme-borland_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BrightLights terminology-theme-brightlights_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Broadcast terminology-theme-broadcast_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Brogrammer terminology-theme-brogrammer_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinDark terminology-theme-builtindark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinLight terminology-theme-builtinlight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinPastelDark terminology-theme-builtinpasteldark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinSolarizedDark terminology-theme-builtinsolarizeddark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinSolarizedLight terminology-theme-builtinsolarizedlight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinTangoDark terminology-theme-builtintangodark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-BuiltinTangoLight terminology-theme-builtintangolight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-C64 terminology-theme-c64_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Calamity terminology-theme-calamity_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Chalk terminology-theme-chalk_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Chalkboard terminology-theme-chalkboard_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ChallengerDeep terminology-theme-challengerdeep_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Chester terminology-theme-chester_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Ciapre terminology-theme-ciapre_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-CLRS terminology-theme-clrs_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Cobalt2 terminology-theme-cobalt2_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-CobaltNeon terminology-theme-cobaltneon_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-CrayonPonyFish terminology-theme-crayonponyfish_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-cyberpunk terminology-theme-cyberpunk_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Dark+ terminology-theme-dark+_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-DarkPastel terminology-theme-darkpastel_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Darkside terminology-theme-darkside_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-deep terminology-theme-deep_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Desert terminology-theme-desert_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-DimmedMonokai terminology-theme-dimmedmonokai_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-DotGov terminology-theme-dotgov_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Dracula terminology-theme-dracula_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-DuotoneDark terminology-theme-duotonedark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Earthsong terminology-theme-earthsong_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Elemental terminology-theme-elemental_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Elementary terminology-theme-elementary_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ENCOM terminology-theme-encom_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Espresso terminology-theme-espresso_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-EspressoLibre terminology-theme-espressolibre_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Fahrenheit terminology-theme-fahrenheit_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Fideloper terminology-theme-fideloper_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-FirefoxDev terminology-theme-firefoxdev_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Firewatch terminology-theme-firewatch_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-FishTank terminology-theme-fishtank_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Flat terminology-theme-flat_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Flatland terminology-theme-flatland_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Floraverse terminology-theme-floraverse_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ForestBlue terminology-theme-forestblue_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Framer terminology-theme-framer_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-FrontEndDelight terminology-theme-frontenddelight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-FunForrest terminology-theme-funforrest_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Galaxy terminology-theme-galaxy_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Github terminology-theme-github_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Glacier terminology-theme-glacier_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Grape terminology-theme-grape_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Grass terminology-theme-grass_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-GruvboxDark terminology-theme-gruvboxdark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Hacktober terminology-theme-hacktober_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Hardcore terminology-theme-hardcore_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Harper terminology-theme-harper_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Highway terminology-theme-highway_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-HipsterGreen terminology-theme-hipstergreen_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Homebrew terminology-theme-homebrew_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Hopscotch terminology-theme-hopscotch_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Hopscotch256 terminology-theme-hopscotch256_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Hurtado terminology-theme-hurtado_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Hybrid terminology-theme-hybrid_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-IC-Green-PPL terminology-theme-ic-green-ppl_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-IC-Orange-PPL terminology-theme-ic-orange-ppl_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-idea terminology-theme-idea_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-idleToes terminology-theme-idletoes_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-IR-Black terminology-theme-ir-black_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-JackieBrown terminology-theme-jackiebrown_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Japanesque terminology-theme-japanesque_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Jellybeans terminology-theme-jellybeans_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-JetBrainsDarcula terminology-theme-jetbrainsdarcula_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Kibble terminology-theme-kibble_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Kolorit terminology-theme-kolorit_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-LabFox terminology-theme-labfox_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-LaterThisEvening terminology-theme-laterthisevening_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Lavandula terminology-theme-lavandula_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-LiquidCarbon terminology-theme-liquidcarbon_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-LiquidCarbonTransparent terminology-theme-liquidcarbontransparent_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-LiquidCarbonTransparentInverse terminology-theme-liquidcarbontransparentinverse_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-lovelace terminology-theme-lovelace_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ManPage terminology-theme-manpage_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Material terminology-theme-material_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-MaterialDark terminology-theme-materialdark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Mathias terminology-theme-mathias_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Medallion terminology-theme-medallion_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Misterioso terminology-theme-misterioso_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Molokai terminology-theme-molokai_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-MonaLisa terminology-theme-monalisa_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-MonokaiRemastered terminology-theme-monokairemastered_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-MonokaiSoda terminology-theme-monokaisoda_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-MonokaiVivid terminology-theme-monokaivivid_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-N0tch2k terminology-theme-n0tch2k_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Neopolitan terminology-theme-neopolitan_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Neutron terminology-theme-neutron_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-NightLionv1 terminology-theme-nightlionv1_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-NightLionv2 terminology-theme-nightlionv2_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-NocturnalWinter terminology-theme-nocturnalwinter_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-nord-flat terminology-theme-nord-flat_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Novel terminology-theme-novel_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Numix terminology-theme-numix_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Obsidian terminology-theme-obsidian_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Ocean terminology-theme-ocean_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-OceanicMaterial terminology-theme-oceanicmaterial_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Ollie terminology-theme-ollie_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-OneHalfDark terminology-theme-onehalfdark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-OneHalfLight terminology-theme-onehalflight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-OperatorMonoDark terminology-theme-operatormonodark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Pandora terminology-theme-pandora_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ParaisoDark terminology-theme-paraisodark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ParasioDark terminology-theme-parasiodark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-PaulMillr terminology-theme-paulmillr_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-PencilDark terminology-theme-pencildark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-PencilLight terminology-theme-pencillight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-PiattoLight terminology-theme-piattolight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Pnevma terminology-theme-pnevma_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Pro terminology-theme-pro_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ProLight terminology-theme-prolight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-purplepeter terminology-theme-purplepeter_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-PurpleRain terminology-theme-purplerain_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-rebecca terminology-theme-rebecca_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-RedAlert terminology-theme-redalert_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-RedPlanet terminology-theme-redplanet_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-RedSands terminology-theme-redsands_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Relaxed terminology-theme-relaxed_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Rippedcasts terminology-theme-rippedcasts_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Royal terminology-theme-royal_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Ryuuko terminology-theme-ryuuko_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SeafoamPastel terminology-theme-seafoampastel_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SeaShells terminology-theme-seashells_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Seti terminology-theme-seti_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Shaman terminology-theme-shaman_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Slate terminology-theme-slate_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Smyck terminology-theme-smyck_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-snazzy terminology-theme-snazzy_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SoftServer terminology-theme-softserver_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SolarizedDarcula terminology-theme-solarizeddarcula_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SolarizedDark terminology-theme-solarizeddark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SolarizedDarkHigherContrast terminology-theme-solarizeddarkhighercontrast_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SolarizedDark-Patched terminology-theme-solarizeddark-patched_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SolarizedLight terminology-theme-solarizedlight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Spacedust terminology-theme-spacedust_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SpaceGray terminology-theme-spacegray_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SpaceGrayEighties terminology-theme-spacegrayeighties_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-SpaceGrayEightiesDull terminology-theme-spacegrayeightiesdull_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Spiderman terminology-theme-spiderman_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Spring terminology-theme-spring_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Square terminology-theme-square_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Sundried terminology-theme-sundried_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Symfonic terminology-theme-symfonic_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-synthwave terminology-theme-synthwave_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TangoAdapted terminology-theme-tangoadapted_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TangoHalfAdapted terminology-theme-tangohalfadapted_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Teerb terminology-theme-teerb_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TerminalBasic terminology-theme-terminalbasic_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ThayerBright terminology-theme-thayerbright_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TheHulk terminology-theme-thehulk_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Tomorrow terminology-theme-tomorrow_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TomorrowNight terminology-theme-tomorrownight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TomorrowNightBlue terminology-theme-tomorrownightblue_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TomorrowNightBright terminology-theme-tomorrownightbright_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TomorrowNightBurns terminology-theme-tomorrownightburns_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-TomorrowNightEighties terminology-theme-tomorrownighteighties_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-ToyChest terminology-theme-toychest_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Treehouse terminology-theme-treehouse_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Twilight terminology-theme-twilight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Ubuntu terminology-theme-ubuntu_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-UltraViolent terminology-theme-ultraviolent_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-UnderTheSea terminology-theme-underthesea_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Urple terminology-theme-urple_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Vaughn terminology-theme-vaughn_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-VibrantInk terminology-theme-vibrantink_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-VioletDark terminology-theme-violetdark_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-VioletLight terminology-theme-violetlight_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-WarmNeon terminology-theme-warmneon_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Wez terminology-theme-wez_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Whimsy terminology-theme-whimsy_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-WildCherry terminology-theme-wildcherry_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Wombat terminology-theme-wombat_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Wryan terminology-theme-wryan_0.1.1bodhi1-1_all.deb
fakeroot dpkg-deb -b terminology-theme-Zenburn terminology-theme-zenburn_0.1.1bodhi1-1_all.deb
